require 'yaml'
require 'erb'
require 'active_record'
require 'fileutils'
require 'cloudkit'

def migrate(env, version=nil)
  ActiveRecord::Base.logger = Logger.new('log/' + env + '.log')
  ActiveRecord::Base.configurations = YAML::load(ERB.new(IO.read(File.dirname(__FILE__) + '/db/config.yml')).result)
  ActiveRecord::Base.establish_connection(env)
  ActiveRecord::Migration.verbose = true
  ActiveRecord::Migrator.migrate(File.dirname(__FILE__) + '/db/migrate', version)
  File.open(File.dirname(__FILE__) + '/db/schema.rb', 'w') do |file|
    ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection, file)
  end
  CloudKit::GWT::Migrator.new(ActiveRecord::Base.connection, File.expand_path(File.dirname(__FILE__))).migrate
  rm_rf('tmp/desktop_sqlite.log')
  rm_rf('tmp/desktop_log.db')
  ActiveRecord::Base.logger = Logger.new('tmp/desktop_sqlite.log')
  ActiveRecord::Migration.verbose = false
  ActiveRecord::Base.establish_connection('desktop_log')
  ActiveRecord::Migrator.migrate(File.dirname(__FILE__) + '/db/migrate', version)
  CloudKit::GWT::SQLiteMirror.new(File.expand_path(File.dirname(__FILE__)) + '/tmp/desktop_sqlite.log').mirror(File.expand_path(File.dirname(__FILE__)) + '/clients/gwt')
end

def reset_db(env)
  migrate(env, 0)
  migrate(env)
end

desc 'start thin in development mode'
task :start do
  sh 'thin --rackup config.ru start'
end

namespace :db do
  desc 'migrate the database'
  task :migrate do
    migrate('development')
  end
  
  desc 'reset the development database'
  task :reset do
    reset_db('development')
  end
end

namespace :test do
  namespace :db do
    desc 'migrate the test database'
    task :migrate do
      migrate('test')
    end
    
    desc 'reset the test database'
    task :reset do
      reset_db('test')
    end
  end
end

namespace :production do
  namespace :db do
    desc 'migrate the production database'
    task :migrate do
      migrate('production')
    end
    
    desc 'reset the production database'
    task :reset do
      reset_db('production')
    end
  end
end

namespace :gwt do
  desc 'compile Java to JavaScript'
  task :compile do
    sh 'clients/gwt/UI-compile'
  end
  
  desc 'run GWT client in hosted mode'
  task :hosted do
    sh 'clients/gwt/UI-shell'
  end
  
  desc 'clean compiled javascript'
  task :clean do
    rm_rf 'public/gwt/ui.UI'
  end
end

namespace :air do
  desc 'assemble AIR assets in a clean directory'
  task :assemble do
    rm_rf 'clients/air/build'
    mkdir 'clients/air/build'
    cp_r 'public/.', 'clients/air/build'
    rm_rf 'clients/air/build/air'
    cp 'clients/air/app.xml', 'clients/air/build'
    cp 'clients/air/app.html', 'clients/air/build'
    cp 'clients/air/AIRAliases.js', 'clients/air/build/gwt/ui.UI'
    cp 'clients/air/servicemonitor.swf', 'clients/air/build/servicemonitor.swf'
  end
  
  desc 'run AIR client in debug mode'
  task :debug => :assemble do
    sh 'adl clients/air/build/app.xml'
  end
  
  desc 'generate a self-signed certificate for development and testing'
  task :certificate do
    air_config = CloudKit::AIR::ApplicationDescriptor.new(File.expand_path(File.dirname(__FILE__)) + '/clients/air/app.xml')
    puts
    print 'Pick a password for your certificate: '
    pass = STDIN.gets.chomp!
    puts
    sh "adt -certificate -cn #{air_config.name}SelfSign 2048-RSA clients/air/#{air_config.name}.p12 #{pass}"
    puts
    puts "Your development/testing certificate has been generated and stored as:\n\n"
    puts "***** clients/air/#{air_config.name}.p12 *****\n\n"
    puts "In order for client app auto-updates to work, each version must use the same\ncertificate and application ID (from app.xml)."
    star_bar
  end
  
  desc 'package AIR app for distribution'
  task :package => :assemble do
    air_config = CloudKit::AIR::ApplicationDescriptor.new(File.expand_path(File.dirname(__FILE__)) + '/clients/air/app.xml')
    if !File.exist?(File.expand_path(File.dirname(__FILE__)) + "/clients/air/#{air_config.name}.p12")
      star_bar
      puts 'A code signing certificate is required prior to packaging an AIR application.'
      Rake::Task['air:certificate'].invoke
    end
    puts "\nPackaging...\n\n"
    puts 'You will be prompted for your certificate password...'
    puts
    sh "adt -package -storetype pkcs12 -keystore clients/air/#{air_config.name}.p12 public/air/#{air_config.name}_#{air_config.version}.air clients/air/build/app.xml -C clients/air/build/ ."
    CloudKit::AIR::Publisher.publish(air_config)
    star_bar
    puts "Your AIR application has been packaged for download or auto-update here:\n\n"
    puts "***** public/air/#{air_config.name}_#{air_config.version}.air *****\n\n"
  end
end
