require 'yaml'
require 'erb'
require 'active_record'
require 'fileutils'

def migrate(env, version=nil)
  ActiveRecord::Base.logger = Logger.new('log/' + env + '.log')
  ActiveRecord::Base.configurations = YAML::load(ERB.new(IO.read(File.dirname(__FILE__) + '/db/config.yml')).result)
  ActiveRecord::Base.establish_connection(env)
  ActiveRecord::Migration.verbose = true
  ActiveRecord::Migrator.migrate(File.dirname(__FILE__) + '/db/migrate', version)
  File.open(File.dirname(__FILE__) + '/db/schema.rb', 'w') do |file|
    ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection, file)
  end
end

def reset_db(env)
  migrate(env, 0)
  migrate(env)
end

desc 'start thin in development mode'
task :start do
  sh 'thin --rackup config.ru start'
end

namespace :db do
  desc 'migrate the database'
  task :migrate do
    migrate('development')
  end
  
  desc 'reset the development database'
  task :reset do
    reset_db('development')
  end
end

namespace :test do
  namespace :db do
    desc 'migrate the test database'
    task :migrate do
      migrate('test')
    end
    
    desc 'reset the test database'
    task :reset do
      reset_db('test')
    end
  end
end

namespace :production do
  namespace :db do
    desc 'migrate the production database'
    task :migrate do
      migrate('production')
    end
    
    desc 'reset the production database'
    task :reset do
      reset_db('production')
    end
  end
end

namespace :gwt do
  desc 'compile Java to JavaScript'
  task :compile do
    sh 'clients/gwt/UI-compile'
  end
  
  desc 'run GWT client in hosted mode'
  task :hosted do
    sh 'clients/gwt/UI-shell'
  end
  
  desc 'clean compiled javascript'
  task :clean do
    rm_rf 'public/gwt/ui.UI'
  end
end

namespace :air do
  desc 'run AIR client in debug mode'
  task :debug do
    rm_rf 'clients/air/build'
    mkdir 'clients/air/build'
    cp_r 'public/.', 'clients/air/build'
    cp 'clients/air/app.xml', 'clients/air/build'
    cp 'clients/air/app.html', 'clients/air/build'
    cp 'clients/air/AIRAliases.js', 'clients/air/build/gwt/ui.UI'
    cp 'clients/air/servicemonitor.swf', 'clients/air/build/servicemonitor.swf'
    sh 'adl clients/air/build/app.xml'
  end
end
